version: '3.9'

services:
  app:
    container_name: todolist_api
    build: .
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: bash -c 'yarn migration:run && yarn dev'
    volumes:
      - .:/app

  db:
    container_name: todolist_db
    image: postgres:latest
    ports:
      - 5433:$PG_PORT
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
